service: api
runtime: nodejs14
env: standard
instance_class: F1
entrypoint: ./berglas exec -- npm start
env_variables:
  PORT: 8080
  LOG_LEVEL: "info"
  NODE_ENV: "production"
  FIREBASE_TYPE: berglas://animemo-secrets/db-username
  FIREBASE_PROJECT_ID: berglas://animemo-secrets/project_id
  FIREBASE_PRIVATE_KEY_ID: berglas://animemo-secrets/private_key_id
  FIREBASE_PRIVATE_KEY: berglas://animemo-secrets/private_key
  FIREBASE_CLIENT_EMAIL: berglas://animemo-secrets/client_email
  FIREBASE_CLIENT_ID: berglas://animemo-secrets/client_id
  FIREBASE_AUTH_URI: berglas://animemo-secrets/auth_uri
  FIREBASE_TOKEN_URI: berglas://animemo-secrets/token_uri
  FIREBASE_AUTH_PROVIDER_X509_CERT_URL: berglas://animemo-secrets/auth_provider_x509_cert_url
  FIREBASE_CLIENT_X509_CERT_URL: berglas://animemo-secrets/client_x509_cert_url