steps:
# Install dependencies
- name: node
  entrypoint: npm
  args: ['install']
# Run tests
- name: node
  entrypoint: npm
  args: ['run', 'test']
# Run build
- name: node
  entrypoint: npm
  args: ['run', 'build']
#  install berglas and add execute permission
- name: gcr.io/cloud-builders/curl
  args: 
    - https://storage.googleapis.com/berglas/master/linux_amd64/berglas
    - --output
    - berglas
- name: ubuntu
  args: 
    - chmod
    - "777"
    - berglas
# Run deploy
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy']
timeout: '1600s'